version: '3.8'

services:
  # 後端服務
  backend:
    build: ./backend
    container_name: comment-system-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/commentsystem
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - comment-system-network

  # 前端服務
  frontend:
    build: ./frontend
    container_name: comment-system-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - comment-system-network

  # 資料庫服務
  db:
    image: postgres:15
    container_name: comment-system-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=commentsystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - comment-system-network

# 定義持久化資料卷
volumes:
  postgres-data:
    driver: local

# 定義網絡
networks:
  comment-system-network:
    driver: bridge